name: SEMANTIC-KERNEL

channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - notebook
  - pyyaml
  - python-dotenv
  - rich
  - pip
  - pip:
    - semantic-kernel
    - chromadb
    - streamlit
    - asyncio







